// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RoslynCodeConverterClientLibrary.Proxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ConvertRequest
    {
        /// <summary>
        /// Initializes a new instance of the ConvertRequest class.
        /// </summary>
        public ConvertRequest() { }

        /// <summary>
        /// Initializes a new instance of the ConvertRequest class.
        /// </summary>
        public ConvertRequest(string code = default(string), string requestedConversion = default(string))
        {
            Code = code;
            RequestedConversion = requestedConversion;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestedConversion")]
        public string RequestedConversion { get; set; }

    }
}
