// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RoslynCodeConverter.Client.Proxies.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConvertResponse
    {
        /// <summary>
        /// Initializes a new instance of the ConvertResponse class.
        /// </summary>
        public ConvertResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConvertResponse class.
        /// </summary>
        public ConvertResponse(bool? conversionOk = default(bool?), string convertedCode = default(string), string errorMessage = default(string))
        {
            ConversionOk = conversionOk;
            ConvertedCode = convertedCode;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conversionOk")]
        public bool? ConversionOk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "convertedCode")]
        public string ConvertedCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
