// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RoslynCodeConverterClientLibrary.Proxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ConvertResponse
    {
        /// <summary>
        /// Initializes a new instance of the ConvertResponse class.
        /// </summary>
        public ConvertResponse() { }

        /// <summary>
        /// Initializes a new instance of the ConvertResponse class.
        /// </summary>
        public ConvertResponse(bool? conversionOk = default(bool?), string convertedCode = default(string), string errorMessage = default(string))
        {
            ConversionOk = conversionOk;
            ConvertedCode = convertedCode;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conversionOk")]
        public bool? ConversionOk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "convertedCode")]
        public string ConvertedCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
